image: "redoxos/redoxer"

stages:
    - build
    - test

cache:
    paths:
        - target/

build:linux:
    stage: build
    script: cargo +nightly build --verbose

build:redox:
    stage: build
    script: redoxer build --verbose

test:linux:
    stage: test
    dependencies:
        - build:linux
    script:
        - cargo +nightly test --verbose -- --test-threads=1
        - cargo +nightly test --verbose --no-default-features -- --test-threads=1

test:redox:
    stage: test
    dependencies:
        - build:redox
    script: redoxer test --verbose

