image: "redoxos/redoxer"

stages:
    - build
    - test

cache:
    paths:
        - target/

build:redox:
    stage: build
    script: redoxer build --verbose

test:redox:
    stage: test
    dependencies:
        - build:redox
    script: redoxer test --verbose
